#ifndef DATA_H
#define DATA_H

#include <stdint.h>
#include "configuration.h"

typedef struct RLK_CONSTANTS
{
    uint64_t rlk00[NUM_OF_PROCESSORS][POLY_LEN];
    uint64_t rlk01[NUM_OF_PROCESSORS][POLY_LEN];
    uint64_t rlk10[NUM_OF_PROCESSORS][POLY_LEN];
    uint64_t rlk11[NUM_OF_PROCESSORS][POLY_LEN];
    uint64_t rlk20[NUM_OF_PROCESSORS][POLY_LEN];
    uint64_t rlk21[NUM_OF_PROCESSORS][POLY_LEN];
    uint64_t rlk30[NUM_OF_PROCESSORS][POLY_LEN];
    uint64_t rlk31[NUM_OF_PROCESSORS][POLY_LEN];
    uint64_t rlk40[NUM_OF_PROCESSORS][POLY_LEN];
    uint64_t rlk41[NUM_OF_PROCESSORS][POLY_LEN];
    uint64_t rlk50[NUM_OF_PROCESSORS][POLY_LEN];
    uint64_t rlk51[NUM_OF_PROCESSORS][POLY_LEN];
} RLK_CONSTANTS;

typedef struct IN_CIPHERTEXT
{
    uint64_t c00[NUM_OF_PROCESSORS][POLY_LEN];
    uint64_t c01[NUM_OF_PROCESSORS][POLY_LEN];
    uint64_t c10[NUM_OF_PROCESSORS][POLY_LEN];
    uint64_t c11[NUM_OF_PROCESSORS][POLY_LEN];
} IN_CIPHERTEXT;

typedef struct OUT_CIPHERTEXT
{
    uint64_t c0[NUM_OF_PROCESSORS][POLY_LEN];
    uint64_t c1[NUM_OF_PROCESSORS][POLY_LEN];
} OUT_CIPHERTEXT;

typedef struct POLYNOMIAL
{
    uint64_t p0[NUM_OF_PROCESSORS+1][POLY_LEN];
    uint64_t p1[NUM_OF_PROCESSORS+1][POLY_LEN];
} POLYNOMIAL;

#endif
